---

yaml-files:
- '*.yaml'
- '*.yml'

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  document-end: disable
  document-start: disable
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
  key-duplicates: enable
  key-ordering: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
  quoted-strings: disable
  trailing-spaces: enable
