// This file is generated by rust-protobuf 2.18.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `actor.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_0;

#[derive(PartialEq,Clone,Default)]
pub struct ActorImages {
    // message fields
    pub avatar: ::std::string::String,
    pub banner: ::std::string::String,
    pub profile1: ::std::string::String,
    pub profile2: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ActorImages {
    fn default() -> &'a ActorImages {
        <ActorImages as ::protobuf::Message>::default_instance()
    }
}

impl ActorImages {
    pub fn new() -> ActorImages {
        ::std::default::Default::default()
    }

    // string avatar = 1;


    pub fn get_avatar(&self) -> &str {
        &self.avatar
    }
    pub fn clear_avatar(&mut self) {
        self.avatar.clear();
    }

    // Param is passed by value, moved
    pub fn set_avatar(&mut self, v: ::std::string::String) {
        self.avatar = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_avatar(&mut self) -> &mut ::std::string::String {
        &mut self.avatar
    }

    // Take field
    pub fn take_avatar(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.avatar, ::std::string::String::new())
    }

    // string banner = 2;


    pub fn get_banner(&self) -> &str {
        &self.banner
    }
    pub fn clear_banner(&mut self) {
        self.banner.clear();
    }

    // Param is passed by value, moved
    pub fn set_banner(&mut self, v: ::std::string::String) {
        self.banner = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_banner(&mut self) -> &mut ::std::string::String {
        &mut self.banner
    }

    // Take field
    pub fn take_banner(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.banner, ::std::string::String::new())
    }

    // string profile1 = 3;


    pub fn get_profile1(&self) -> &str {
        &self.profile1
    }
    pub fn clear_profile1(&mut self) {
        self.profile1.clear();
    }

    // Param is passed by value, moved
    pub fn set_profile1(&mut self, v: ::std::string::String) {
        self.profile1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_profile1(&mut self) -> &mut ::std::string::String {
        &mut self.profile1
    }

    // Take field
    pub fn take_profile1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.profile1, ::std::string::String::new())
    }

    // string profile2 = 4;


    pub fn get_profile2(&self) -> &str {
        &self.profile2
    }
    pub fn clear_profile2(&mut self) {
        self.profile2.clear();
    }

    // Param is passed by value, moved
    pub fn set_profile2(&mut self, v: ::std::string::String) {
        self.profile2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_profile2(&mut self) -> &mut ::std::string::String {
        &mut self.profile2
    }

    // Take field
    pub fn take_profile2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.profile2, ::std::string::String::new())
    }
}

impl ::protobuf::Message for ActorImages {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.avatar)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.banner)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.profile1)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.profile2)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.avatar.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.avatar);
        }
        if !self.banner.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.banner);
        }
        if !self.profile1.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.profile1);
        }
        if !self.profile2.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.profile2);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.avatar.is_empty() {
            os.write_string(1, &self.avatar)?;
        }
        if !self.banner.is_empty() {
            os.write_string(2, &self.banner)?;
        }
        if !self.profile1.is_empty() {
            os.write_string(3, &self.profile1)?;
        }
        if !self.profile2.is_empty() {
            os.write_string(4, &self.profile2)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ActorImages {
        ActorImages::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "avatar",
                |m: &ActorImages| { &m.avatar },
                |m: &mut ActorImages| { &mut m.avatar },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "banner",
                |m: &ActorImages| { &m.banner },
                |m: &mut ActorImages| { &mut m.banner },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "profile1",
                |m: &ActorImages| { &m.profile1 },
                |m: &mut ActorImages| { &mut m.profile1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "profile2",
                |m: &ActorImages| { &m.profile2 },
                |m: &mut ActorImages| { &mut m.profile2 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ActorImages>(
                "ActorImages",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ActorImages {
        static instance: ::protobuf::rt::LazyV2<ActorImages> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ActorImages::new)
    }
}

impl ::protobuf::Clear for ActorImages {
    fn clear(&mut self) {
        self.avatar.clear();
        self.banner.clear();
        self.profile1.clear();
        self.profile2.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ActorImages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ActorImages {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct CareerStatus {
    // message fields
    pub started: ::protobuf::SingularPtrField<super::common::Date>,
    pub is_active: bool,
    pub retried: ::protobuf::SingularPtrField<super::common::Date>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a CareerStatus {
    fn default() -> &'a CareerStatus {
        <CareerStatus as ::protobuf::Message>::default_instance()
    }
}

impl CareerStatus {
    pub fn new() -> CareerStatus {
        ::std::default::Default::default()
    }

    // .Date started = 1;


    pub fn get_started(&self) -> &super::common::Date {
        self.started.as_ref().unwrap_or_else(|| <super::common::Date as ::protobuf::Message>::default_instance())
    }
    pub fn clear_started(&mut self) {
        self.started.clear();
    }

    pub fn has_started(&self) -> bool {
        self.started.is_some()
    }

    // Param is passed by value, moved
    pub fn set_started(&mut self, v: super::common::Date) {
        self.started = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_started(&mut self) -> &mut super::common::Date {
        if self.started.is_none() {
            self.started.set_default();
        }
        self.started.as_mut().unwrap()
    }

    // Take field
    pub fn take_started(&mut self) -> super::common::Date {
        self.started.take().unwrap_or_else(|| super::common::Date::new())
    }

    // bool is_active = 2;


    pub fn get_is_active(&self) -> bool {
        self.is_active
    }
    pub fn clear_is_active(&mut self) {
        self.is_active = false;
    }

    // Param is passed by value, moved
    pub fn set_is_active(&mut self, v: bool) {
        self.is_active = v;
    }

    // .Date retried = 3;


    pub fn get_retried(&self) -> &super::common::Date {
        self.retried.as_ref().unwrap_or_else(|| <super::common::Date as ::protobuf::Message>::default_instance())
    }
    pub fn clear_retried(&mut self) {
        self.retried.clear();
    }

    pub fn has_retried(&self) -> bool {
        self.retried.is_some()
    }

    // Param is passed by value, moved
    pub fn set_retried(&mut self, v: super::common::Date) {
        self.retried = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_retried(&mut self) -> &mut super::common::Date {
        if self.retried.is_none() {
            self.retried.set_default();
        }
        self.retried.as_mut().unwrap()
    }

    // Take field
    pub fn take_retried(&mut self) -> super::common::Date {
        self.retried.take().unwrap_or_else(|| super::common::Date::new())
    }
}

impl ::protobuf::Message for CareerStatus {
    fn is_initialized(&self) -> bool {
        for v in &self.started {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.retried {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.started)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.is_active = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.retried)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.started.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.is_active != false {
            my_size += 2;
        }
        if let Some(ref v) = self.retried.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.started.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.is_active != false {
            os.write_bool(2, self.is_active)?;
        }
        if let Some(ref v) = self.retried.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> CareerStatus {
        CareerStatus::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::Date>>(
                "started",
                |m: &CareerStatus| { &m.started },
                |m: &mut CareerStatus| { &mut m.started },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "is_active",
                |m: &CareerStatus| { &m.is_active },
                |m: &mut CareerStatus| { &mut m.is_active },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::Date>>(
                "retried",
                |m: &CareerStatus| { &m.retried },
                |m: &mut CareerStatus| { &mut m.retried },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<CareerStatus>(
                "CareerStatus",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static CareerStatus {
        static instance: ::protobuf::rt::LazyV2<CareerStatus> = ::protobuf::rt::LazyV2::INIT;
        instance.get(CareerStatus::new)
    }
}

impl ::protobuf::Clear for CareerStatus {
    fn clear(&mut self) {
        self.started.clear();
        self.is_active = false;
        self.retried.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for CareerStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CareerStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Actor {
    // message fields
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    pub aliases: ::protobuf::RepeatedField<::std::string::String>,
    pub name_patterns: ::protobuf::RepeatedField<::std::string::String>,
    pub gender: ::protobuf::SingularPtrField<super::common::Gender>,
    pub nationality: ::std::string::String,
    pub dob: ::protobuf::SingularPtrField<super::common::Date>,
    pub description: ::std::string::String,
    pub career_status: ::protobuf::SingularPtrField<CareerStatus>,
    pub images: ::protobuf::SingularPtrField<ActorImages>,
    pub sundry: ::protobuf::SingularPtrField<super::common::SundryThings>,
    pub added_on: ::protobuf::SingularPtrField<super::common::DateTime>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Actor {
    fn default() -> &'a Actor {
        <Actor as ::protobuf::Message>::default_instance()
    }
}

impl Actor {
    pub fn new() -> Actor {
        ::std::default::Default::default()
    }

    // string id = 1;


    pub fn get_id(&self) -> &str {
        &self.id
    }
    pub fn clear_id(&mut self) {
        self.id.clear();
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: ::std::string::String) {
        self.id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_id(&mut self) -> &mut ::std::string::String {
        &mut self.id
    }

    // Take field
    pub fn take_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.id, ::std::string::String::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // repeated string aliases = 3;


    pub fn get_aliases(&self) -> &[::std::string::String] {
        &self.aliases
    }
    pub fn clear_aliases(&mut self) {
        self.aliases.clear();
    }

    // Param is passed by value, moved
    pub fn set_aliases(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.aliases = v;
    }

    // Mutable pointer to the field.
    pub fn mut_aliases(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.aliases
    }

    // Take field
    pub fn take_aliases(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.aliases, ::protobuf::RepeatedField::new())
    }

    // repeated string name_patterns = 4;


    pub fn get_name_patterns(&self) -> &[::std::string::String] {
        &self.name_patterns
    }
    pub fn clear_name_patterns(&mut self) {
        self.name_patterns.clear();
    }

    // Param is passed by value, moved
    pub fn set_name_patterns(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.name_patterns = v;
    }

    // Mutable pointer to the field.
    pub fn mut_name_patterns(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.name_patterns
    }

    // Take field
    pub fn take_name_patterns(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.name_patterns, ::protobuf::RepeatedField::new())
    }

    // .Gender gender = 5;


    pub fn get_gender(&self) -> &super::common::Gender {
        self.gender.as_ref().unwrap_or_else(|| <super::common::Gender as ::protobuf::Message>::default_instance())
    }
    pub fn clear_gender(&mut self) {
        self.gender.clear();
    }

    pub fn has_gender(&self) -> bool {
        self.gender.is_some()
    }

    // Param is passed by value, moved
    pub fn set_gender(&mut self, v: super::common::Gender) {
        self.gender = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_gender(&mut self) -> &mut super::common::Gender {
        if self.gender.is_none() {
            self.gender.set_default();
        }
        self.gender.as_mut().unwrap()
    }

    // Take field
    pub fn take_gender(&mut self) -> super::common::Gender {
        self.gender.take().unwrap_or_else(|| super::common::Gender::new())
    }

    // string nationality = 7;


    pub fn get_nationality(&self) -> &str {
        &self.nationality
    }
    pub fn clear_nationality(&mut self) {
        self.nationality.clear();
    }

    // Param is passed by value, moved
    pub fn set_nationality(&mut self, v: ::std::string::String) {
        self.nationality = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nationality(&mut self) -> &mut ::std::string::String {
        &mut self.nationality
    }

    // Take field
    pub fn take_nationality(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.nationality, ::std::string::String::new())
    }

    // .Date dob = 8;


    pub fn get_dob(&self) -> &super::common::Date {
        self.dob.as_ref().unwrap_or_else(|| <super::common::Date as ::protobuf::Message>::default_instance())
    }
    pub fn clear_dob(&mut self) {
        self.dob.clear();
    }

    pub fn has_dob(&self) -> bool {
        self.dob.is_some()
    }

    // Param is passed by value, moved
    pub fn set_dob(&mut self, v: super::common::Date) {
        self.dob = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dob(&mut self) -> &mut super::common::Date {
        if self.dob.is_none() {
            self.dob.set_default();
        }
        self.dob.as_mut().unwrap()
    }

    // Take field
    pub fn take_dob(&mut self) -> super::common::Date {
        self.dob.take().unwrap_or_else(|| super::common::Date::new())
    }

    // string description = 9;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }

    // .CareerStatus career_status = 10;


    pub fn get_career_status(&self) -> &CareerStatus {
        self.career_status.as_ref().unwrap_or_else(|| <CareerStatus as ::protobuf::Message>::default_instance())
    }
    pub fn clear_career_status(&mut self) {
        self.career_status.clear();
    }

    pub fn has_career_status(&self) -> bool {
        self.career_status.is_some()
    }

    // Param is passed by value, moved
    pub fn set_career_status(&mut self, v: CareerStatus) {
        self.career_status = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_career_status(&mut self) -> &mut CareerStatus {
        if self.career_status.is_none() {
            self.career_status.set_default();
        }
        self.career_status.as_mut().unwrap()
    }

    // Take field
    pub fn take_career_status(&mut self) -> CareerStatus {
        self.career_status.take().unwrap_or_else(|| CareerStatus::new())
    }

    // .ActorImages images = 11;


    pub fn get_images(&self) -> &ActorImages {
        self.images.as_ref().unwrap_or_else(|| <ActorImages as ::protobuf::Message>::default_instance())
    }
    pub fn clear_images(&mut self) {
        self.images.clear();
    }

    pub fn has_images(&self) -> bool {
        self.images.is_some()
    }

    // Param is passed by value, moved
    pub fn set_images(&mut self, v: ActorImages) {
        self.images = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_images(&mut self) -> &mut ActorImages {
        if self.images.is_none() {
            self.images.set_default();
        }
        self.images.as_mut().unwrap()
    }

    // Take field
    pub fn take_images(&mut self) -> ActorImages {
        self.images.take().unwrap_or_else(|| ActorImages::new())
    }

    // .SundryThings sundry = 12;


    pub fn get_sundry(&self) -> &super::common::SundryThings {
        self.sundry.as_ref().unwrap_or_else(|| <super::common::SundryThings as ::protobuf::Message>::default_instance())
    }
    pub fn clear_sundry(&mut self) {
        self.sundry.clear();
    }

    pub fn has_sundry(&self) -> bool {
        self.sundry.is_some()
    }

    // Param is passed by value, moved
    pub fn set_sundry(&mut self, v: super::common::SundryThings) {
        self.sundry = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_sundry(&mut self) -> &mut super::common::SundryThings {
        if self.sundry.is_none() {
            self.sundry.set_default();
        }
        self.sundry.as_mut().unwrap()
    }

    // Take field
    pub fn take_sundry(&mut self) -> super::common::SundryThings {
        self.sundry.take().unwrap_or_else(|| super::common::SundryThings::new())
    }

    // .DateTime added_on = 350;


    pub fn get_added_on(&self) -> &super::common::DateTime {
        self.added_on.as_ref().unwrap_or_else(|| <super::common::DateTime as ::protobuf::Message>::default_instance())
    }
    pub fn clear_added_on(&mut self) {
        self.added_on.clear();
    }

    pub fn has_added_on(&self) -> bool {
        self.added_on.is_some()
    }

    // Param is passed by value, moved
    pub fn set_added_on(&mut self, v: super::common::DateTime) {
        self.added_on = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_added_on(&mut self) -> &mut super::common::DateTime {
        if self.added_on.is_none() {
            self.added_on.set_default();
        }
        self.added_on.as_mut().unwrap()
    }

    // Take field
    pub fn take_added_on(&mut self) -> super::common::DateTime {
        self.added_on.take().unwrap_or_else(|| super::common::DateTime::new())
    }
}

impl ::protobuf::Message for Actor {
    fn is_initialized(&self) -> bool {
        for v in &self.gender {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.dob {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.career_status {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.images {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.sundry {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.added_on {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.aliases)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.name_patterns)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.gender)?;
                },
                7 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.nationality)?;
                },
                8 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.dob)?;
                },
                9 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                10 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.career_status)?;
                },
                11 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.images)?;
                },
                12 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.sundry)?;
                },
                350 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.added_on)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        for value in &self.aliases {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        for value in &self.name_patterns {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        if let Some(ref v) = self.gender.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.nationality.is_empty() {
            my_size += ::protobuf::rt::string_size(7, &self.nationality);
        }
        if let Some(ref v) = self.dob.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.description);
        }
        if let Some(ref v) = self.career_status.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.images.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.sundry.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.added_on.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        for v in &self.aliases {
            os.write_string(3, &v)?;
        };
        for v in &self.name_patterns {
            os.write_string(4, &v)?;
        };
        if let Some(ref v) = self.gender.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.nationality.is_empty() {
            os.write_string(7, &self.nationality)?;
        }
        if let Some(ref v) = self.dob.as_ref() {
            os.write_tag(8, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.description.is_empty() {
            os.write_string(9, &self.description)?;
        }
        if let Some(ref v) = self.career_status.as_ref() {
            os.write_tag(10, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.images.as_ref() {
            os.write_tag(11, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.sundry.as_ref() {
            os.write_tag(12, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.added_on.as_ref() {
            os.write_tag(350, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Actor {
        Actor::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "id",
                |m: &Actor| { &m.id },
                |m: &mut Actor| { &mut m.id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &Actor| { &m.name },
                |m: &mut Actor| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "aliases",
                |m: &Actor| { &m.aliases },
                |m: &mut Actor| { &mut m.aliases },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name_patterns",
                |m: &Actor| { &m.name_patterns },
                |m: &mut Actor| { &mut m.name_patterns },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::Gender>>(
                "gender",
                |m: &Actor| { &m.gender },
                |m: &mut Actor| { &mut m.gender },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "nationality",
                |m: &Actor| { &m.nationality },
                |m: &mut Actor| { &mut m.nationality },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::Date>>(
                "dob",
                |m: &Actor| { &m.dob },
                |m: &mut Actor| { &mut m.dob },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &Actor| { &m.description },
                |m: &mut Actor| { &mut m.description },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<CareerStatus>>(
                "career_status",
                |m: &Actor| { &m.career_status },
                |m: &mut Actor| { &mut m.career_status },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ActorImages>>(
                "images",
                |m: &Actor| { &m.images },
                |m: &mut Actor| { &mut m.images },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::SundryThings>>(
                "sundry",
                |m: &Actor| { &m.sundry },
                |m: &mut Actor| { &mut m.sundry },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::DateTime>>(
                "added_on",
                |m: &Actor| { &m.added_on },
                |m: &mut Actor| { &mut m.added_on },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Actor>(
                "Actor",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Actor {
        static instance: ::protobuf::rt::LazyV2<Actor> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Actor::new)
    }
}

impl ::protobuf::Clear for Actor {
    fn clear(&mut self) {
        self.id.clear();
        self.name.clear();
        self.aliases.clear();
        self.name_patterns.clear();
        self.gender.clear();
        self.nationality.clear();
        self.dob.clear();
        self.description.clear();
        self.career_status.clear();
        self.images.clear();
        self.sundry.clear();
        self.added_on.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Actor {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Actor {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bactor.proto\x1a\x0ccommon.proto\"u\n\x0bActorImages\x12\x16\n\x06a\
    vatar\x18\x01\x20\x01(\tR\x06avatar\x12\x16\n\x06banner\x18\x02\x20\x01(\
    \tR\x06banner\x12\x1a\n\x08profile1\x18\x03\x20\x01(\tR\x08profile1\x12\
    \x1a\n\x08profile2\x18\x04\x20\x01(\tR\x08profile2\"m\n\x0cCareerStatus\
    \x12\x1f\n\x07started\x18\x01\x20\x01(\x0b2\x05.DateR\x07started\x12\x1b\
    \n\tis_active\x18\x02\x20\x01(\x08R\x08isActive\x12\x1f\n\x07retried\x18\
    \x03\x20\x01(\x0b2\x05.DateR\x07retried\"\x90\x03\n\x05Actor\x12\x0e\n\
    \x02id\x18\x01\x20\x01(\tR\x02id\x12\x12\n\x04name\x18\x02\x20\x01(\tR\
    \x04name\x12\x18\n\x07aliases\x18\x03\x20\x03(\tR\x07aliases\x12#\n\rnam\
    e_patterns\x18\x04\x20\x03(\tR\x0cnamePatterns\x12\x1f\n\x06gender\x18\
    \x05\x20\x01(\x0b2\x07.GenderR\x06gender\x12\x20\n\x0bnationality\x18\
    \x07\x20\x01(\tR\x0bnationality\x12\x17\n\x03dob\x18\x08\x20\x01(\x0b2\
    \x05.DateR\x03dob\x12\x20\n\x0bdescription\x18\t\x20\x01(\tR\x0bdescript\
    ion\x122\n\rcareer_status\x18\n\x20\x01(\x0b2\r.CareerStatusR\x0ccareerS\
    tatus\x12$\n\x06images\x18\x0b\x20\x01(\x0b2\x0c.ActorImagesR\x06images\
    \x12%\n\x06sundry\x18\x0c\x20\x01(\x0b2\r.SundryThingsR\x06sundry\x12%\n\
    \x08added_on\x18\xde\x02\x20\x01(\x0b2\t.DateTimeR\x07addedOnJ\x96\t\n\
    \x06\x12\x04\0\0\x1e\x02\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\x02\x03\0\
    \x12\x03\x02\0\x16\n\n\n\x02\x04\0\x12\x04\x04\0\t\x01\n\n\n\x03\x04\0\
    \x01\x12\x03\x04\x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x04\x16\n\
    \x0c\n\x05\x04\0\x02\0\x05\x12\x03\x05\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\
    \x12\x03\x05\x0b\x11\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x05\x14\x15\n\
    \x0b\n\x04\x04\0\x02\x01\x12\x03\x06\x04\x16\n\x0c\n\x05\x04\0\x02\x01\
    \x05\x12\x03\x06\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\x0b\x11\
    \n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\x14\x15\n\x0b\n\x04\x04\0\x02\
    \x02\x12\x03\x07\x04\x18\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x07\x04\n\
    \n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x07\x0b\x13\n\x0c\n\x05\x04\0\x02\
    \x02\x03\x12\x03\x07\x16\x17\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x08\x04\
    \x18\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x08\x04\n\n\x0c\n\x05\x04\0\
    \x02\x03\x01\x12\x03\x08\x0b\x13\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\
    \x08\x16\x17\n\n\n\x02\x04\x01\x12\x04\x0b\0\x0f\x01\n\n\n\x03\x04\x01\
    \x01\x12\x03\x0b\x08\x14\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x0c\x04\x15\n\
    \x0c\n\x05\x04\x01\x02\0\x06\x12\x03\x0c\x04\x08\n\x0c\n\x05\x04\x01\x02\
    \0\x01\x12\x03\x0c\t\x10\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x0c\x13\
    \x14\n\x0b\n\x04\x04\x01\x02\x01\x12\x03\r\x04\x17\n\x0c\n\x05\x04\x01\
    \x02\x01\x05\x12\x03\r\x04\x08\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\r\
    \t\x12\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\r\x15\x16\n\x0b\n\x04\x04\
    \x01\x02\x02\x12\x03\x0e\x04\x15\n\x0c\n\x05\x04\x01\x02\x02\x06\x12\x03\
    \x0e\x04\x08\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x0e\t\x10\n\x0c\n\
    \x05\x04\x01\x02\x02\x03\x12\x03\x0e\x13\x14\n\n\n\x02\x04\x02\x12\x04\
    \x11\0\x1e\x01\n\n\n\x03\x04\x02\x01\x12\x03\x11\x08\r\n\x0b\n\x04\x04\
    \x02\x02\0\x12\x03\x12\x04\x12\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x12\
    \x04\n\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x12\x0b\r\n\x0c\n\x05\x04\
    \x02\x02\0\x03\x12\x03\x12\x10\x11\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\
    \x13\x04\x14\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\x13\x04\n\n\x0c\n\
    \x05\x04\x02\x02\x01\x01\x12\x03\x13\x0b\x0f\n\x0c\n\x05\x04\x02\x02\x01\
    \x03\x12\x03\x13\x12\x13\n\x0b\n\x04\x04\x02\x02\x02\x12\x03\x14\x04\x20\
    \n\x0c\n\x05\x04\x02\x02\x02\x04\x12\x03\x14\x04\x0c\n\x0c\n\x05\x04\x02\
    \x02\x02\x05\x12\x03\x14\r\x13\n\x0c\n\x05\x04\x02\x02\x02\x01\x12\x03\
    \x14\x14\x1b\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x14\x1e\x1f\n\x0b\n\
    \x04\x04\x02\x02\x03\x12\x03\x15\x04&\n\x0c\n\x05\x04\x02\x02\x03\x04\
    \x12\x03\x15\x04\x0c\n\x0c\n\x05\x04\x02\x02\x03\x05\x12\x03\x15\r\x13\n\
    \x0c\n\x05\x04\x02\x02\x03\x01\x12\x03\x15\x14!\n\x0c\n\x05\x04\x02\x02\
    \x03\x03\x12\x03\x15$%\n\x0b\n\x04\x04\x02\x02\x04\x12\x03\x16\x04\x16\n\
    \x0c\n\x05\x04\x02\x02\x04\x06\x12\x03\x16\x04\n\n\x0c\n\x05\x04\x02\x02\
    \x04\x01\x12\x03\x16\x0b\x11\n\x0c\n\x05\x04\x02\x02\x04\x03\x12\x03\x16\
    \x14\x15\n\x0b\n\x04\x04\x02\x02\x05\x12\x03\x17\x04\x1b\n\x0c\n\x05\x04\
    \x02\x02\x05\x05\x12\x03\x17\x04\n\n\x0c\n\x05\x04\x02\x02\x05\x01\x12\
    \x03\x17\x0b\x16\n\x0c\n\x05\x04\x02\x02\x05\x03\x12\x03\x17\x19\x1a\n\
    \x0b\n\x04\x04\x02\x02\x06\x12\x03\x18\x04\x11\n\x0c\n\x05\x04\x02\x02\
    \x06\x06\x12\x03\x18\x04\x08\n\x0c\n\x05\x04\x02\x02\x06\x01\x12\x03\x18\
    \t\x0c\n\x0c\n\x05\x04\x02\x02\x06\x03\x12\x03\x18\x0f\x10\n\x0b\n\x04\
    \x04\x02\x02\x07\x12\x03\x19\x04\x1b\n\x0c\n\x05\x04\x02\x02\x07\x05\x12\
    \x03\x19\x04\n\n\x0c\n\x05\x04\x02\x02\x07\x01\x12\x03\x19\x0b\x16\n\x0c\
    \n\x05\x04\x02\x02\x07\x03\x12\x03\x19\x19\x1a\n\x0b\n\x04\x04\x02\x02\
    \x08\x12\x03\x1a\x04$\n\x0c\n\x05\x04\x02\x02\x08\x06\x12\x03\x1a\x04\
    \x10\n\x0c\n\x05\x04\x02\x02\x08\x01\x12\x03\x1a\x11\x1e\n\x0c\n\x05\x04\
    \x02\x02\x08\x03\x12\x03\x1a!#\n\x0b\n\x04\x04\x02\x02\t\x12\x03\x1b\x04\
    \x1c\n\x0c\n\x05\x04\x02\x02\t\x06\x12\x03\x1b\x04\x0f\n\x0c\n\x05\x04\
    \x02\x02\t\x01\x12\x03\x1b\x10\x16\n\x0c\n\x05\x04\x02\x02\t\x03\x12\x03\
    \x1b\x19\x1b\n\x0b\n\x04\x04\x02\x02\n\x12\x03\x1c\x04\x1d\n\x0c\n\x05\
    \x04\x02\x02\n\x06\x12\x03\x1c\x04\x10\n\x0c\n\x05\x04\x02\x02\n\x01\x12\
    \x03\x1c\x11\x17\n\x0c\n\x05\x04\x02\x02\n\x03\x12\x03\x1c\x1a\x1c\n\x0b\
    \n\x04\x04\x02\x02\x0b\x12\x03\x1d\x04\x1c\n\x0c\n\x05\x04\x02\x02\x0b\
    \x06\x12\x03\x1d\x04\x0c\n\x0c\n\x05\x04\x02\x02\x0b\x01\x12\x03\x1d\r\
    \x15\n\x0c\n\x05\x04\x02\x02\x0b\x03\x12\x03\x1d\x18\x1bb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
