//! Contains all of the files generated by protobuf.

pub mod actor;
pub mod art_common;
pub mod common;
pub mod custom;
pub mod game;
pub mod image;
pub mod manga;
pub mod network;
pub mod site;
pub mod studio;
pub mod tag;
pub mod video;
