// This file is generated by rust-protobuf 2.18.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `tag.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_0;

#[derive(PartialEq,Clone,Default)]
pub struct Tag {
    // message fields
    pub id: ::std::string::String,
    pub name: ::std::string::String,
    pub applicable_to: ::std::vec::Vec<super::common::ApplicableTo>,
    pub also_adds: ::protobuf::RepeatedField<::std::string::String>,
    pub aliases: ::protobuf::RepeatedField<::std::string::String>,
    pub added_on: ::protobuf::SingularPtrField<super::common::DateTime>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Tag {
    fn default() -> &'a Tag {
        <Tag as ::protobuf::Message>::default_instance()
    }
}

impl Tag {
    pub fn new() -> Tag {
        ::std::default::Default::default()
    }

    // string id = 1;


    pub fn get_id(&self) -> &str {
        &self.id
    }
    pub fn clear_id(&mut self) {
        self.id.clear();
    }

    // Param is passed by value, moved
    pub fn set_id(&mut self, v: ::std::string::String) {
        self.id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_id(&mut self) -> &mut ::std::string::String {
        &mut self.id
    }

    // Take field
    pub fn take_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.id, ::std::string::String::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // repeated .ApplicableTo applicable_to = 3;


    pub fn get_applicable_to(&self) -> &[super::common::ApplicableTo] {
        &self.applicable_to
    }
    pub fn clear_applicable_to(&mut self) {
        self.applicable_to.clear();
    }

    // Param is passed by value, moved
    pub fn set_applicable_to(&mut self, v: ::std::vec::Vec<super::common::ApplicableTo>) {
        self.applicable_to = v;
    }

    // Mutable pointer to the field.
    pub fn mut_applicable_to(&mut self) -> &mut ::std::vec::Vec<super::common::ApplicableTo> {
        &mut self.applicable_to
    }

    // Take field
    pub fn take_applicable_to(&mut self) -> ::std::vec::Vec<super::common::ApplicableTo> {
        ::std::mem::replace(&mut self.applicable_to, ::std::vec::Vec::new())
    }

    // repeated string also_adds = 4;


    pub fn get_also_adds(&self) -> &[::std::string::String] {
        &self.also_adds
    }
    pub fn clear_also_adds(&mut self) {
        self.also_adds.clear();
    }

    // Param is passed by value, moved
    pub fn set_also_adds(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.also_adds = v;
    }

    // Mutable pointer to the field.
    pub fn mut_also_adds(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.also_adds
    }

    // Take field
    pub fn take_also_adds(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.also_adds, ::protobuf::RepeatedField::new())
    }

    // repeated string aliases = 5;


    pub fn get_aliases(&self) -> &[::std::string::String] {
        &self.aliases
    }
    pub fn clear_aliases(&mut self) {
        self.aliases.clear();
    }

    // Param is passed by value, moved
    pub fn set_aliases(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.aliases = v;
    }

    // Mutable pointer to the field.
    pub fn mut_aliases(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.aliases
    }

    // Take field
    pub fn take_aliases(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.aliases, ::protobuf::RepeatedField::new())
    }

    // .DateTime added_on = 350;


    pub fn get_added_on(&self) -> &super::common::DateTime {
        self.added_on.as_ref().unwrap_or_else(|| <super::common::DateTime as ::protobuf::Message>::default_instance())
    }
    pub fn clear_added_on(&mut self) {
        self.added_on.clear();
    }

    pub fn has_added_on(&self) -> bool {
        self.added_on.is_some()
    }

    // Param is passed by value, moved
    pub fn set_added_on(&mut self, v: super::common::DateTime) {
        self.added_on = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_added_on(&mut self) -> &mut super::common::DateTime {
        if self.added_on.is_none() {
            self.added_on.set_default();
        }
        self.added_on.as_mut().unwrap()
    }

    // Take field
    pub fn take_added_on(&mut self) -> super::common::DateTime {
        self.added_on.take().unwrap_or_else(|| super::common::DateTime::new())
    }
}

impl ::protobuf::Message for Tag {
    fn is_initialized(&self) -> bool {
        for v in &self.added_on {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_enum_with_unknown_fields_into(wire_type, is, &mut self.applicable_to, 3, &mut self.unknown_fields)?
                },
                4 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.also_adds)?;
                },
                5 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.aliases)?;
                },
                350 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.added_on)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        for value in &self.applicable_to {
            my_size += ::protobuf::rt::enum_size(3, *value);
        };
        for value in &self.also_adds {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        for value in &self.aliases {
            my_size += ::protobuf::rt::string_size(5, &value);
        };
        if let Some(ref v) = self.added_on.as_ref() {
            let len = v.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        for v in &self.applicable_to {
            os.write_enum(3, ::protobuf::ProtobufEnum::value(v))?;
        };
        for v in &self.also_adds {
            os.write_string(4, &v)?;
        };
        for v in &self.aliases {
            os.write_string(5, &v)?;
        };
        if let Some(ref v) = self.added_on.as_ref() {
            os.write_tag(350, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Tag {
        Tag::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "id",
                |m: &Tag| { &m.id },
                |m: &mut Tag| { &mut m.id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &Tag| { &m.name },
                |m: &mut Tag| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::common::ApplicableTo>>(
                "applicable_to",
                |m: &Tag| { &m.applicable_to },
                |m: &mut Tag| { &mut m.applicable_to },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "also_adds",
                |m: &Tag| { &m.also_adds },
                |m: &mut Tag| { &mut m.also_adds },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "aliases",
                |m: &Tag| { &m.aliases },
                |m: &mut Tag| { &mut m.aliases },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::common::DateTime>>(
                "added_on",
                |m: &Tag| { &m.added_on },
                |m: &mut Tag| { &mut m.added_on },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Tag>(
                "Tag",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Tag {
        static instance: ::protobuf::rt::LazyV2<Tag> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Tag::new)
    }
}

impl ::protobuf::Clear for Tag {
    fn clear(&mut self) {
        self.id.clear();
        self.name.clear();
        self.applicable_to.clear();
        self.also_adds.clear();
        self.aliases.clear();
        self.added_on.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Tag {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Tag {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\ttag.proto\x1a\x0ccommon.proto\"\xbb\x01\n\x03Tag\x12\x0e\n\x02id\x18\
    \x01\x20\x01(\tR\x02id\x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04name\x12\
    2\n\rapplicable_to\x18\x03\x20\x03(\x0e2\r.ApplicableToR\x0capplicableTo\
    \x12\x1b\n\talso_adds\x18\x04\x20\x03(\tR\x08alsoAdds\x12\x18\n\x07alias\
    es\x18\x05\x20\x03(\tR\x07aliases\x12%\n\x08added_on\x18\xde\x02\x20\x01\
    (\x0b2\t.DateTimeR\x07addedOnJ\xd4\x03\n\x06\x12\x04\0\0\x0b\x02\n\x08\n\
    \x01\x0c\x12\x03\0\0\x12\n\t\n\x02\x03\0\x12\x03\x01\0\x16\n5\n\x02\x04\
    \0\x12\x04\x04\0\x0b\x01\x1a)\x20The\x20tag\x20as\x20it\x20is\x20stored\
    \x20in\x20the\x20database\n\n\n\n\x03\x04\0\x01\x12\x03\x04\x08\x0b\n\
    \x0b\n\x04\x04\0\x02\0\x12\x03\x05\x04\x12\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x05\x04\n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\x0b\r\n\x0c\n\
    \x05\x04\0\x02\0\x03\x12\x03\x05\x10\x11\n\x0b\n\x04\x04\0\x02\x01\x12\
    \x03\x06\x04\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x04\n\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x06\x0b\x0f\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x06\x12\x13\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x07\x04,\n\x0c\n\
    \x05\x04\0\x02\x02\x04\x12\x03\x07\x04\x0c\n\x0c\n\x05\x04\0\x02\x02\x06\
    \x12\x03\x07\r\x19\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x07\x1a'\n\x0c\
    \n\x05\x04\0\x02\x02\x03\x12\x03\x07*+\n\x0b\n\x04\x04\0\x02\x03\x12\x03\
    \x08\x04\"\n\x0c\n\x05\x04\0\x02\x03\x04\x12\x03\x08\x04\x0c\n\x0c\n\x05\
    \x04\0\x02\x03\x05\x12\x03\x08\r\x13\n\x0c\n\x05\x04\0\x02\x03\x01\x12\
    \x03\x08\x14\x1d\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x08\x20!\n\x0b\n\
    \x04\x04\0\x02\x04\x12\x03\t\x04\x20\n\x0c\n\x05\x04\0\x02\x04\x04\x12\
    \x03\t\x04\x0c\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\t\r\x13\n\x0c\n\x05\
    \x04\0\x02\x04\x01\x12\x03\t\x14\x1b\n\x0c\n\x05\x04\0\x02\x04\x03\x12\
    \x03\t\x1e\x1f\n\x0b\n\x04\x04\0\x02\x05\x12\x03\n\x04\x1c\n\x0c\n\x05\
    \x04\0\x02\x05\x06\x12\x03\n\x04\x0c\n\x0c\n\x05\x04\0\x02\x05\x01\x12\
    \x03\n\r\x15\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\n\x18\x1bb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
